# Generated by Django 4.1.3 on 2022-11-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='company',
        ),
        migrations.AddField(
            model_name='stock',
            name='crypto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='easy_to_borrow',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fractionable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='id_alpaca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='maintenance_margin_requirement',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='marginable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_order_size',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_trade_increment',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_increment',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='shortable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='tradable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
