# Generated by Django 4.1.3 on 2022-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_stock_company_stock_crypto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='crypto',
            new_name='class_alpaca',
        ),
        migrations.AddField(
            model_name='stock',
            name='origin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
