# Generated by Django 4.1.3 on 2022-11-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_stock_easy_to_borrow_alter_stock_fractionable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_price',
            name='timeframe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
