# Generated by Django 4.1.3 on 2022-11-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_whatch_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whatch_list',
            new_name='watch_list',
        ),
    ]
