# Generated by Django 4.1.3 on 2022-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_rename_whatch_list_watch_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='watch_list',
            options={'verbose_name': 'Tipo de Ator', 'verbose_name_plural': 'Tipos de Atores'},
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='adjusted_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
