# Generated by Django 4.1.3 on 2022-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_stock_options_alter_watch_list_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_price',
            name='adjusted_close',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='close',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='high',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='low',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='open',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='volume',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
