# Generated by Django 3.2.16 on 2022-12-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_auto_20221204_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='detected_patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_pattern', models.CharField(blank=True, max_length=30, null=True)),
                ('detection_method', models.CharField(blank=True, max_length=30, null=True)),
                ('stock_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.stock_price')),
            ],
        ),
    ]
